Module Images
    Friend ReadOnly LeftWall As New TextCanvas(New List(Of String) From
        {
            "XX            ",
            "  XX          ",
            "    XX        ",
            "      XX      ",
            "        XX    ",
            "          XX  ",
            "            XX",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "            XX",
            "          XX  ",
            "        XX    ",
            "      XX      ",
            "    XX        ",
            "  XX          ",
            "XX            "
        })
    Friend ReadOnly LeftDoor As New TextCanvas(New List(Of String) From
        {
            "XX            ",
            "  XX          ",
            "    XX        ",
            "      XX      ",
            "        XX    ",
            "          XX  ",
            "            XX",
            "    XXX       ",
            "    X  XX     ",
            "    X    X    ",
            "    X    X    ",
            "    X    X    ",
            "    X    X    ",
            "    X    X    ",
            "    X    X    ",
            "    X    X    ",
            "    X    X    ",
            "    X    X    ",
            "    X    X    ",
            "    X    X    ",
            "    X    X    ",
            "    X    X  XX",
            "    X    XXX  ",
            "    X   XX    ",
            "    X XX      ",
            "    XX        ",
            "  XX          ",
            "XX            "
        })
    Friend ReadOnly AheadWall As New TextCanvas(New List(Of String) From
        {
            "                            ",
            "                            ",
            "                            ",
            "                            ",
            "                            ",
            "                            ",
            "                            ",
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
            "X                          X",
            "X                          X",
            "X                          X",
            "X                          X",
            "X                          X",
            "X                          X",
            "X                          X",
            "X                          X",
            "X                          X",
            "X                          X",
            "X                          X",
            "X                          X",
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
            "                            ",
            "                            ",
            "                            ",
            "                            ",
            "                            ",
            "                            ",
            "                            "
        })
    Friend ReadOnly AheadDoor As New TextCanvas(New List(Of String) From
        {
            "                            ",
            "                            ",
            "                            ",
            "                            ",
            "                            ",
            "                            ",
            "                            ",
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
            "X                          X",
            "X                          X",
            "X      XXXXXXXXXXXXXX      X",
            "X      X            X      X",
            "X      X            X      X",
            "X      X            X      X",
            "X      X            X      X",
            "X      X            X      X",
            "X      X            X      X",
            "X      X            X      X",
            "X      X            X      X",
            "X      X            X      X",
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
            "                            ",
            "                            ",
            "                            ",
            "                            ",
            "                            ",
            "                            ",
            "                            "
        })
    Friend ReadOnly RightWall As New TextCanvas(New List(Of String) From
        {
            "            XX",
            "          XX  ",
            "        XX    ",
            "      XX      ",
            "    XX        ",
            "  XX          ",
            "XX            ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "XX            ",
            "  XX          ",
            "    XX        ",
            "      XX      ",
            "        XX    ",
            "          XX  ",
            "            XX"
        })
    Friend ReadOnly RightDoor As New TextCanvas(New List(Of String) From
        {
            "            XX",
            "          XX  ",
            "        XX    ",
            "      XX      ",
            "    XX        ",
            "  XX          ",
            "XX            ",
            "       XXX    ",
            "     XX  X    ",
            "    X    X    ",
            "    X    X    ",
            "    X    X    ",
            "    X    X    ",
            "    X    X    ",
            "    X    X    ",
            "    X    X    ",
            "    X    X    ",
            "    X    X    ",
            "    X    X    ",
            "    X    X    ",
            "    X    X    ",
            "XX  X    X    ",
            "  XXX    X    ",
            "    XX   X    ",
            "      XX X    ",
            "        XX    ",
            "          XX  ",
            "            XX"
        })
End Module
