Module Tokens
    Friend Const AroundText = "around"
    Friend Const CharacterText = "character"
    Friend Const CharactersText = "characters"
    Friend Const CreateText = "create"
    Friend Const DropText = "drop"
    Friend Const DungeonText = "dungeon"
    Friend Const DungeonsText = "dungeons"
    Friend Const EnterText = "enter"
    Friend Const GroundText = "ground"
    Friend Const HelpText = "help"
    Friend Const InventoryText = "inventory"
    Friend Const LeftText = "left"
    Friend Const MoveText = "move"
    Friend Const RightText = "right"
    Friend Const StatusText = "status"
    Friend Const SwitchText = "switch"
    Friend Const TakeText = "take"
End Module
