Module Tokens
    Friend Const AllText = "all"
    Friend Const AroundText = "around"
    Friend Const CharacterText = "character"
    Friend Const CharactersText = "characters"
    Friend Const CreateText = "create"
    Friend Const DeleteText = "delete"
    Friend Const DropText = "drop"
    Friend Const DungeonText = "dungeon"
    Friend Const DungeonsText = "dungeons"
    Friend Const EnemiesText = "enemies"
    Friend Const EnterText = "enter"
    Friend Const EquipText = "equip"
    Friend Const FightText = "fight"
    Friend Const GroundText = "ground"
    Friend Const HelpText = "help"
    Friend Const InventoryText = "inventory"
    Friend Const LeftText = "left"
    Friend Const LookText = "look"
    Friend Const MoveText = "move"
    Friend Const RestText = "rest"
    Friend Const RightText = "right"
    Friend Const StatusText = "status"
    Friend Const SwitchText = "switch"
    Friend Const TakeText = "take"
    Friend Const UseText = "use"
End Module
