Module WallImages
    Friend ReadOnly LeftWall As New TextCanvas(New List(Of String) From
        {
            "XX            ",
            "  XX          ",
            "    XX        ",
            "      XX      ",
            "        XX    ",
            "          XX  ",
            "            XX",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "            XX",
            "          XX  ",
            "        XX    ",
            "      XX      ",
            "    XX        ",
            "  XX          ",
            "XX            "
        })
    Friend ReadOnly AheadWall As New TextCanvas(New List(Of String) From
        {
            "                            ",
            "                            ",
            "                            ",
            "                            ",
            "                            ",
            "                            ",
            "                            ",
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
            "X                          X",
            "X                          X",
            "X                          X",
            "X                          X",
            "X                          X",
            "X                          X",
            "X                          X",
            "X                          X",
            "X                          X",
            "X                          X",
            "X                          X",
            "X                          X",
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
            "                            ",
            "                            ",
            "                            ",
            "                            ",
            "                            ",
            "                            ",
            "                            "
        })
    Friend ReadOnly RightWall As New TextCanvas(New List(Of String) From
        {
            "            XX",
            "          XX  ",
            "        XX    ",
            "      XX      ",
            "    XX        ",
            "  XX          ",
            "XX            ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "XX            ",
            "  XX          ",
            "    XX        ",
            "      XX      ",
            "        XX    ",
            "          XX  ",
            "            XX"
        })
End Module
