Module WallImages
    Friend ReadOnly LeftWall As New TextCanvas(New List(Of String) From
        {
            "\_            ",
            "  \_          ",
            "    \_        ",
            "      \_      ",
            "        \_    ",
            "          \_  ",
            "            \_",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "            _/",
            "          _/  ",
            "        _/    ",
            "      _/      ",
            "    _/        ",
            "  _/          ",
            "_/            "
        })
    Friend ReadOnly AheadWall As New TextCanvas(New List(Of String) From
        {
            "                            ",
            "                            ",
            "                            ",
            "                            ",
            "                            ",
            "                            ",
            "                            ",
            "+--------------------------+",
            "|                          |",
            "|                          |",
            "|                          |",
            "|                          |",
            "|                          |",
            "|                          |",
            "|                          |",
            "|                          |",
            "|                          |",
            "|                          |",
            "|                          |",
            "|                          |",
            "+--------------------------+",
            "                            ",
            "                            ",
            "                            ",
            "                            ",
            "                            ",
            "                            ",
            "                            "
        })
    Friend ReadOnly RightWall As New TextCanvas(New List(Of String) From
        {
            "            _/",
            "          _/  ",
            "        _/    ",
            "      _/      ",
            "    _/        ",
            "  _/          ",
            "_/            ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "\_            ",
            "  \_          ",
            "    \_        ",
            "      \_      ",
            "        \_    ",
            "          \_  ",
            "            \_"
        })
End Module
